/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaginaPrincipal;
import Controlador.EventoPaginaPrincipal;
import java.awt.Color;
/**
 *
 * @author user1
 */
public class PaginaPrincipal extends javax.swing.JFrame {
EventoPaginaPrincipal accion = new EventoPaginaPrincipal ();
    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
        this.setTitle("Pagina Principal");
        this.setExtendedState(6);
        this.getContentPane().setBackground(Color.white);
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaInicio = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cambiarPanelMenu = new javax.swing.JPanel();
        bReporte = new rsbuttom.RSButtonMetro();
        bServicio = new rsbuttom.RSButtonMetro();
        bInicio = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cajaInicio.setBackground(new java.awt.Color(221, 87, 76));

        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        bsalir.setContentAreaFilled(false);
        bsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLÍNICA DE IMPRESORAS");

        javax.swing.GroupLayout cajaInicioLayout = new javax.swing.GroupLayout(cajaInicio);
        cajaInicio.setLayout(cajaInicioLayout);
        cajaInicioLayout.setHorizontalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addGap(529, 529, 529)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaInicioLayout.setVerticalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelCambio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo.png"))); // NOI18N

        javax.swing.GroupLayout PanelCambioLayout = new javax.swing.GroupLayout(PanelCambio);
        PanelCambio.setLayout(PanelCambioLayout);
        PanelCambioLayout.setHorizontalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        PanelCambioLayout.setVerticalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(606, Short.MAX_VALUE))
        );

        cambiarPanelMenu.setBackground(new java.awt.Color(220, 220, 220));

        bReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono reporte.png"))); // NOI18N
        bReporte.setText("   Reportes");
        bReporte.setColorHover(new java.awt.Color(176, 173, 173));
        bReporte.setColorNormal(new java.awt.Color(220, 220, 220));
        bReporte.setColorPressed(new java.awt.Color(127, 126, 126));
        bReporte.setColorTextNormal(new java.awt.Color(65, 64, 64));
        bReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        bServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono servicios.png"))); // NOI18N
        bServicio.setText("   Servicios");
        bServicio.setColorHover(new java.awt.Color(176, 173, 173));
        bServicio.setColorNormal(new java.awt.Color(220, 220, 220));
        bServicio.setColorPressed(new java.awt.Color(127, 126, 126));
        bServicio.setColorTextNormal(new java.awt.Color(65, 64, 64));
        bServicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServicioActionPerformed(evt);
            }
        });

        bInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono casa.png"))); // NOI18N
        bInicio.setText("   Inicio/Orden de Trabajo");
        bInicio.setColorHover(new java.awt.Color(176, 173, 173));
        bInicio.setColorNormal(new java.awt.Color(220, 220, 220));
        bInicio.setColorPressed(new java.awt.Color(127, 126, 126));
        bInicio.setColorTextNormal(new java.awt.Color(65, 64, 64));
        bInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarPanelMenuLayout = new javax.swing.GroupLayout(cambiarPanelMenu);
        cambiarPanelMenu.setLayout(cambiarPanelMenuLayout);
        cambiarPanelMenuLayout.setHorizontalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        cambiarPanelMenuLayout.setVerticalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cajaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cambiarPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cajaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bsalirActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
       accion.botonReportes(PanelCambio);
    }//GEN-LAST:event_bReporteActionPerformed

    private void bServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServicioActionPerformed
      accion.botonServicio(PanelCambio);
    }//GEN-LAST:event_bServicioActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
      accion.botonIncio(PanelCambio);
    }//GEN-LAST:event_bInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCambio;
    private rsbuttom.RSButtonMetro bInicio;
    private rsbuttom.RSButtonMetro bReporte;
    private rsbuttom.RSButtonMetro bServicio;
    private javax.swing.JButton bsalir;
    private javax.swing.JPanel cajaInicio;
    private javax.swing.JPanel cambiarPanelMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
