/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaginaPrincipal;

import Controlador.EventoTeclas;
import Controlador.Reporte.EventoAbonado;
import Controlador.Reporte.EventoCliente;
import Controlador.Reporte.EventoHistorico;
import Controlador.Reporte.EventoMayorMenor;
import Controlador.Reporte.EventoNoPagada;
import Controlador.Reporte.EventoOrdenes;
import Controlador.Reporte.EventoPagada;

/**
 *
 * @author user1
 */
public class PanelReportes extends javax.swing.JPanel {

    EventoTeclas teclas = new EventoTeclas();
    EventoOrdenes ordenes = new EventoOrdenes();
    EventoHistorico historico = new EventoHistorico();
    EventoMayorMenor mayorMenor = new EventoMayorMenor();
    EventoCliente cliente = new EventoCliente();
    EventoPagada pagada = new EventoPagada();
    EventoNoPagada noPagada = new EventoNoPagada();
    EventoAbonado abonado = new EventoAbonado();

    public PanelReportes() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Orden = new javax.swing.JPanel();
        fBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEncontrados = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cEstadoOrden = new javax.swing.JComboBox();
        fNumOrden = new javax.swing.JTextField();
        fNombreEmpresa = new javax.swing.JTextField();
        fNombre = new javax.swing.JTextField();
        fAbono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fTotal = new javax.swing.JTextField();
        jModificar = new javax.swing.JButton();
        JBuscar = new rsbuttom.RSButtonMetro();
        Historico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHistorico = new javax.swing.JTable();
        jGuardarHistorico = new rsbuttom.RSButtonMetro();
        jBuscarHistorico = new rsbuttom.RSButtonMetro();
        MayorAMenor = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOrden = new javax.swing.JTable();
        jGuardarMayor = new rsbuttom.RSButtonMetro();
        jBuscarMayor = new rsbuttom.RSButtonMetro();
        Clientes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        fBuscarCliente = new javax.swing.JTextField();
        fTotalCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        JBuscarCliente = new rsbuttom.RSButtonMetro();
        jGuardarCliente = new rsbuttom.RSButtonMetro();
        Pagadas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaPagadas = new javax.swing.JTable();
        fTotalPagada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jGuardarPagadas = new rsbuttom.RSButtonMetro();
        jBuscarPagadas = new rsbuttom.RSButtonMetro();
        Abonadas = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaAbonada = new javax.swing.JTable();
        fTotalAbono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fTotalPendiente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jGuardarAbonadas = new rsbuttom.RSButtonMetro();
        jBuscarAbonadas = new rsbuttom.RSButtonMetro();
        NoPagadas = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaNoPagadas = new javax.swing.JTable();
        fTotalNoPagado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jGuardarNoPagadas = new rsbuttom.RSButtonMetro();
        jBuscarNoPagadas = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        fBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fBuscarKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("INGRESE NOMBRE DEL CLIENTE");

        jListEncontrados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 102, 0))); // NOI18N
        jListEncontrados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jListEncontrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEncontradosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEncontrados);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nº. DE ORDEN:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("NOMBRE DE EMPRESA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NOMBRE Y APELLIDO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ESTADO:");

        cEstadoOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAGADO", "ABONADO", "NO PAGADO" }));
        cEstadoOrden.setEnabled(false);

        fNumOrden.setEditable(false);

        fNombreEmpresa.setEditable(false);

        fNombre.setEditable(false);

        fAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fAbonoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("ABONO:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("TOTAL:");

        fTotal.setEditable(false);

        jModificar.setText("MODIFCAR");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        JBuscar.setBackground(new java.awt.Color(255, 51, 51));
        JBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        JBuscar.setText("BUSCAR");
        JBuscar.setColorHover(new java.awt.Color(153, 0, 0));
        JBuscar.setColorNormal(new java.awt.Color(255, 51, 51));
        JBuscar.setColorPressed(new java.awt.Color(204, 0, 0));
        JBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrdenLayout = new javax.swing.GroupLayout(Orden);
        Orden.setLayout(OrdenLayout);
        OrdenLayout.setHorizontalGroup(
            OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrdenLayout.createSequentialGroup()
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OrdenLayout.createSequentialGroup()
                                .addComponent(fBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(603, Short.MAX_VALUE))
                    .addGroup(OrdenLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrdenLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OrdenLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(OrdenLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(OrdenLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(OrdenLayout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(OrdenLayout.createSequentialGroup()
                                            .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(OrdenLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 339, Short.MAX_VALUE))))
        );
        OrdenLayout.setVerticalGroup(
            OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdenLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrdenLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrdenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDENES", Orden);

        tablaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "SERVICIO", "PRECIO", "ESTADO"
            }
        ));
        tablaHistorico.setEnabled(false);
        jScrollPane2.setViewportView(tablaHistorico);

        jGuardarHistorico.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarHistorico.setText("GUARDAR");
        jGuardarHistorico.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarHistorico.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarHistorico.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarHistorico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarHistoricoActionPerformed(evt);
            }
        });

        jBuscarHistorico.setBackground(new java.awt.Color(255, 51, 51));
        jBuscarHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        jBuscarHistorico.setText("BUSCAR");
        jBuscarHistorico.setColorHover(new java.awt.Color(153, 0, 0));
        jBuscarHistorico.setColorNormal(new java.awt.Color(255, 51, 51));
        jBuscarHistorico.setColorPressed(new java.awt.Color(204, 0, 0));
        jBuscarHistorico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBuscarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HistoricoLayout = new javax.swing.GroupLayout(Historico);
        Historico.setLayout(HistoricoLayout);
        HistoricoLayout.setHorizontalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoricoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoricoLayout.createSequentialGroup()
                        .addComponent(jBuscarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jGuardarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(486, Short.MAX_VALUE))
        );
        HistoricoLayout.setVerticalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoricoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HISTÓRICO", Historico);

        tableOrden.setAutoCreateRowSorter(true);
        tableOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "SERVICIO", "CANTIDAD", "PRECIO ", "TOTAL"
            }
        ));
        jScrollPane3.setViewportView(tableOrden);
        if (tableOrden.getColumnModel().getColumnCount() > 0) {
            tableOrden.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableOrden.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableOrden.getColumnModel().getColumn(2).setHeaderValue("CANTIDAD");
            tableOrden.getColumnModel().getColumn(3).setResizable(false);
            tableOrden.getColumnModel().getColumn(3).setHeaderValue("PRECIO ");
            tableOrden.getColumnModel().getColumn(4).setHeaderValue("TOTAL");
        }

        jGuardarMayor.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarMayor.setText("GUARDAR");
        jGuardarMayor.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarMayor.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarMayor.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarMayor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarMayorActionPerformed(evt);
            }
        });

        jBuscarMayor.setBackground(new java.awt.Color(255, 51, 51));
        jBuscarMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        jBuscarMayor.setText("BUSCAR");
        jBuscarMayor.setColorHover(new java.awt.Color(153, 0, 0));
        jBuscarMayor.setColorNormal(new java.awt.Color(255, 51, 51));
        jBuscarMayor.setColorPressed(new java.awt.Color(204, 0, 0));
        jBuscarMayor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBuscarMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MayorAMenorLayout = new javax.swing.GroupLayout(MayorAMenor);
        MayorAMenor.setLayout(MayorAMenorLayout);
        MayorAMenorLayout.setHorizontalGroup(
            MayorAMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MayorAMenorLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MayorAMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MayorAMenorLayout.createSequentialGroup()
                        .addComponent(jBuscarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jGuardarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        MayorAMenorLayout.setVerticalGroup(
            MayorAMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MayorAMenorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MayorAMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SERVICIOS DE MAYOR A MENOR", MayorAMenor);

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO DE ORDEN", "VALOR"
            }
        ));
        tablaCliente.setEnabled(false);
        jScrollPane4.setViewportView(tablaCliente);
        if (tablaCliente.getColumnModel().getColumnCount() > 0) {
            tablaCliente.getColumnModel().getColumn(0).setPreferredWidth(200);
            tablaCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("INGRESE NOMBRE DEL CLIENTE");

        fBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fBuscarClienteKeyTyped(evt);
            }
        });

        fTotalCliente.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("VALOR TOTAL DE LAS ORDENES:");

        lNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lNombre.setText("NOMBRE DEL CLIENTE");

        JBuscarCliente.setBackground(new java.awt.Color(255, 51, 51));
        JBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        JBuscarCliente.setText("BUSCAR");
        JBuscarCliente.setColorHover(new java.awt.Color(153, 0, 0));
        JBuscarCliente.setColorNormal(new java.awt.Color(255, 51, 51));
        JBuscarCliente.setColorPressed(new java.awt.Color(204, 0, 0));
        JBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBuscarClienteActionPerformed(evt);
            }
        });

        jGuardarCliente.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarCliente.setText("GUARDAR");
        jGuardarCliente.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarCliente.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarCliente.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addComponent(fBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(JBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ClientesLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fTotalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTotalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLIENTE", Clientes);

        tablaPagadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO DE ORDEN", "VALOR PAGADO"
            }
        ));
        tablaPagadas.setEnabled(false);
        jScrollPane5.setViewportView(tablaPagadas);
        if (tablaPagadas.getColumnModel().getColumnCount() > 0) {
            tablaPagadas.getColumnModel().getColumn(0).setPreferredWidth(200);
            tablaPagadas.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        fTotalPagada.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("VALOR TOTAL PAGADO:");

        jGuardarPagadas.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarPagadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarPagadas.setText("GUARDAR");
        jGuardarPagadas.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarPagadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarPagadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarPagadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarPagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarPagadasActionPerformed(evt);
            }
        });

        jBuscarPagadas.setBackground(new java.awt.Color(255, 51, 51));
        jBuscarPagadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        jBuscarPagadas.setText("BUSCAR");
        jBuscarPagadas.setColorHover(new java.awt.Color(153, 0, 0));
        jBuscarPagadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jBuscarPagadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jBuscarPagadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBuscarPagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarPagadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PagadasLayout = new javax.swing.GroupLayout(Pagadas);
        Pagadas.setLayout(PagadasLayout);
        PagadasLayout.setHorizontalGroup(
            PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagadasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PagadasLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(fTotalPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PagadasLayout.createSequentialGroup()
                        .addComponent(jBuscarPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jGuardarPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        PagadasLayout.setVerticalGroup(
            PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagadasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscarPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGuardarPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTotalPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PAGADAS", Pagadas);

        tablaAbonada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO DE ORDEN", "VALOR ABONADO", "SALDO PENDIENTE"
            }
        ));
        tablaAbonada.setEnabled(false);
        jScrollPane6.setViewportView(tablaAbonada);
        if (tablaAbonada.getColumnModel().getColumnCount() > 0) {
            tablaAbonada.getColumnModel().getColumn(0).setPreferredWidth(200);
            tablaAbonada.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        fTotalAbono.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("TOTAL ABONADO");

        fTotalPendiente.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("TOTAL PENDIENTE");

        jGuardarAbonadas.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarAbonadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarAbonadas.setText("GUARDAR");
        jGuardarAbonadas.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarAbonadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarAbonadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarAbonadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarAbonadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarAbonadasActionPerformed(evt);
            }
        });

        jBuscarAbonadas.setBackground(new java.awt.Color(255, 51, 51));
        jBuscarAbonadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        jBuscarAbonadas.setText("BUSCAR");
        jBuscarAbonadas.setColorHover(new java.awt.Color(153, 0, 0));
        jBuscarAbonadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jBuscarAbonadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jBuscarAbonadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBuscarAbonadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarAbonadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbonadasLayout = new javax.swing.GroupLayout(Abonadas);
        Abonadas.setLayout(AbonadasLayout);
        AbonadasLayout.setHorizontalGroup(
            AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbonadasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbonadasLayout.createSequentialGroup()
                        .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(fTotalAbono))
                        .addGap(18, 18, 18)
                        .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fTotalPendiente)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addGroup(AbonadasLayout.createSequentialGroup()
                        .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AbonadasLayout.createSequentialGroup()
                                .addComponent(jBuscarAbonadas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jGuardarAbonadas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        AbonadasLayout.setVerticalGroup(
            AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbonadasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscarAbonadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGuardarAbonadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTotalAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTotalPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbonadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ABONADAS", Abonadas);

        tablaNoPagadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO DE ORDEN", "VALOR NO PAGADO"
            }
        ));
        tablaNoPagadas.setEnabled(false);
        jScrollPane7.setViewportView(tablaNoPagadas);
        if (tablaNoPagadas.getColumnModel().getColumnCount() > 0) {
            tablaNoPagadas.getColumnModel().getColumn(0).setPreferredWidth(200);
            tablaNoPagadas.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        fTotalNoPagado.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("VALOR TOTAL NO PAGADO:");

        jGuardarNoPagadas.setBackground(new java.awt.Color(255, 51, 51));
        jGuardarNoPagadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        jGuardarNoPagadas.setText("GUARDAR");
        jGuardarNoPagadas.setColorHover(new java.awt.Color(153, 0, 0));
        jGuardarNoPagadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jGuardarNoPagadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jGuardarNoPagadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarNoPagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarNoPagadasActionPerformed(evt);
            }
        });

        jBuscarNoPagadas.setBackground(new java.awt.Color(255, 51, 51));
        jBuscarNoPagadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        jBuscarNoPagadas.setText("BUSCAR");
        jBuscarNoPagadas.setColorHover(new java.awt.Color(153, 0, 0));
        jBuscarNoPagadas.setColorNormal(new java.awt.Color(255, 51, 51));
        jBuscarNoPagadas.setColorPressed(new java.awt.Color(204, 0, 0));
        jBuscarNoPagadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBuscarNoPagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarNoPagadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NoPagadasLayout = new javax.swing.GroupLayout(NoPagadas);
        NoPagadas.setLayout(NoPagadasLayout);
        NoPagadasLayout.setHorizontalGroup(
            NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoPagadasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoPagadasLayout.createSequentialGroup()
                        .addComponent(jBuscarNoPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jGuardarNoPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(NoPagadasLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(fTotalNoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        NoPagadasLayout.setVerticalGroup(
            NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoPagadasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscarNoPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGuardarNoPagadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NoPagadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTotalNoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NO PAGADAS", NoPagadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        ordenes.modificar(fBuscar, jListEncontrados, fAbono, fTotal, fNumOrden, fNombreEmpresa, fNombre, cEstadoOrden);
    }//GEN-LAST:event_jModificarActionPerformed

    private void jListEncontradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEncontradosValueChanged
        ordenes.encontrados(jListEncontrados, fNombreEmpresa, fNombre, fNumOrden, cEstadoOrden, fAbono, fTotal);
    }//GEN-LAST:event_jListEncontradosValueChanged


    private void JBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarActionPerformed
        ordenes.ActualizarLista(fBuscar, jListEncontrados);
    }//GEN-LAST:event_JBuscarActionPerformed

    private void jGuardarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarHistoricoActionPerformed
        historico.guardar(tablaHistorico);
    }//GEN-LAST:event_jGuardarHistoricoActionPerformed

    private void jBuscarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarHistoricoActionPerformed
        historico.buscar(tablaHistorico);
    }//GEN-LAST:event_jBuscarHistoricoActionPerformed

    private void jGuardarMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarMayorActionPerformed
        mayorMenor.guardar(tableOrden);
    }//GEN-LAST:event_jGuardarMayorActionPerformed

    private void jBuscarMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarMayorActionPerformed
        mayorMenor.mostrar(tableOrden);
        mayorMenor.limpiar();
    }//GEN-LAST:event_jBuscarMayorActionPerformed
  
    private void fAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAbonoKeyTyped
       teclas.numeros(evt);
    }//GEN-LAST:event_fAbonoKeyTyped

    private void fBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBuscarKeyTyped
        teclas.letraMayuscula(evt);
    }//GEN-LAST:event_fBuscarKeyTyped

    private void JBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarClienteActionPerformed
        cliente.buscar(fBuscarCliente, tablaCliente, lNombre, fTotalCliente);
    }//GEN-LAST:event_JBuscarClienteActionPerformed

    private void jGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarClienteActionPerformed
        cliente.guardar(tablaCliente, lNombre);
    }//GEN-LAST:event_jGuardarClienteActionPerformed

    private void fBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBuscarClienteKeyTyped
        teclas.letraMayuscula(evt);
    }//GEN-LAST:event_fBuscarClienteKeyTyped

    private void jGuardarNoPagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarNoPagadasActionPerformed
        noPagada.guardar(tablaNoPagadas);
    }//GEN-LAST:event_jGuardarNoPagadasActionPerformed

    private void jBuscarNoPagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarNoPagadasActionPerformed
        noPagada.buscar(tablaNoPagadas, fTotalNoPagado);
    }//GEN-LAST:event_jBuscarNoPagadasActionPerformed

    private void jGuardarPagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarPagadasActionPerformed
        pagada.guardar(tablaPagadas);
    }//GEN-LAST:event_jGuardarPagadasActionPerformed

    private void jBuscarPagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarPagadasActionPerformed
        pagada.buscar(tablaPagadas, fTotalPagada);
    }//GEN-LAST:event_jBuscarPagadasActionPerformed

    private void jGuardarAbonadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarAbonadasActionPerformed
        abonado.guardar(tablaAbonada);
    }//GEN-LAST:event_jGuardarAbonadasActionPerformed

    private void jBuscarAbonadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarAbonadasActionPerformed
        abonado.buscar(tablaAbonada, fTotalAbono, fTotalPendiente);
    }//GEN-LAST:event_jBuscarAbonadasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Abonadas;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Historico;
    private rsbuttom.RSButtonMetro JBuscar;
    private rsbuttom.RSButtonMetro JBuscarCliente;
    private javax.swing.JPanel MayorAMenor;
    private javax.swing.JPanel NoPagadas;
    private javax.swing.JPanel Orden;
    private javax.swing.JPanel Pagadas;
    private javax.swing.JComboBox cEstadoOrden;
    private javax.swing.JTextField fAbono;
    private javax.swing.JTextField fBuscar;
    private javax.swing.JTextField fBuscarCliente;
    private javax.swing.JTextField fNombre;
    private javax.swing.JTextField fNombreEmpresa;
    private javax.swing.JTextField fNumOrden;
    private javax.swing.JTextField fTotal;
    private javax.swing.JTextField fTotalAbono;
    private javax.swing.JTextField fTotalCliente;
    private javax.swing.JTextField fTotalNoPagado;
    private javax.swing.JTextField fTotalPagada;
    private javax.swing.JTextField fTotalPendiente;
    private rsbuttom.RSButtonMetro jBuscarAbonadas;
    private rsbuttom.RSButtonMetro jBuscarHistorico;
    private rsbuttom.RSButtonMetro jBuscarMayor;
    private rsbuttom.RSButtonMetro jBuscarNoPagadas;
    private rsbuttom.RSButtonMetro jBuscarPagadas;
    private rsbuttom.RSButtonMetro jGuardarAbonadas;
    private rsbuttom.RSButtonMetro jGuardarCliente;
    private rsbuttom.RSButtonMetro jGuardarHistorico;
    private rsbuttom.RSButtonMetro jGuardarMayor;
    private rsbuttom.RSButtonMetro jGuardarNoPagadas;
    private rsbuttom.RSButtonMetro jGuardarPagadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListEncontrados;
    private javax.swing.JButton jModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lNombre;
    private javax.swing.JTable tablaAbonada;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaHistorico;
    private javax.swing.JTable tablaNoPagadas;
    private javax.swing.JTable tablaPagadas;
    private javax.swing.JTable tableOrden;
    // End of variables declaration//GEN-END:variables

}
