/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaginaPrincipal;

import Controlador.EventoTeclas;
import Controlador.Servicio.EventoAgregar;
import Controlador.Servicio.EventoBuscar;
import Controlador.Servicio.EventoModificar;


/**
 *
 * @author user1
 */
public class PanelServicios extends javax.swing.JPanel {
   
    int id = 0;
    EventoAgregar agregar = new EventoAgregar();
    EventoTeclas tecla = new EventoTeclas();
    EventoBuscar buscar = new EventoBuscar();
    EventoModificar modificar = new EventoModificar();

    public PanelServicios() {
        initComponents();
        this.fEstado.setVisible(false);
        agregar.generar(fId);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Agregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fPrecioA = new javax.swing.JTextField();
        fNombreServicioA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fId = new javax.swing.JTextField();
        jAgregar1 = new rsbuttom.RSButtonMetro();
        Buscar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fConsultar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nuevo_doc = new javax.swing.JLabel();
        JBuscar = new rsbuttom.RSButtonMetro();
        Modificar = new javax.swing.JPanel();
        fModificar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEncontrados = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fPrecioM = new javax.swing.JTextField();
        fNombreServicioM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FIdM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cEstado = new javax.swing.JComboBox();
        JBuscarM = new rsbuttom.RSButtonMetro();
        JModificar = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE DEL SERVICIO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PRECIO:");

        fPrecioA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fPrecioAKeyTyped(evt);
            }
        });

        fNombreServicioA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNombreServicioAKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("dólares");

        fEstado.setEditable(false);
        fEstado.setText("ACTIVO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ID:");

        fId.setEditable(false);
        fId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jAgregar1.setBackground(new java.awt.Color(255, 51, 51));
        jAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoAgregar.png"))); // NOI18N
        jAgregar1.setText("AGREGAR");
        jAgregar1.setColorHover(new java.awt.Color(153, 0, 0));
        jAgregar1.setColorNormal(new java.awt.Color(255, 51, 51));
        jAgregar1.setColorPressed(new java.awt.Color(204, 0, 0));
        jAgregar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNombreServicioA, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addComponent(fPrecioA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addComponent(fId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(261, 261, 261)
                                .addComponent(fEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(fNombreServicioA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fPrecioA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AGREGAR", Agregar);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("INGRESE EL NOMBRE DEL SERVICIO A BUSCAR");

        fConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fConsultarKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel10.setText("<html><h2>Resultados de su Busqueda</h2><hr></html>");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nuevo_doc.setBackground(new java.awt.Color(153, 180, 209));
        nuevo_doc.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(nuevo_doc);

        JBuscar.setBackground(new java.awt.Color(255, 51, 51));
        JBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        JBuscar.setText("BUSCAR");
        JBuscar.setColorHover(new java.awt.Color(153, 0, 0));
        JBuscar.setColorNormal(new java.awt.Color(255, 51, 51));
        JBuscar.setColorPressed(new java.awt.Color(204, 0, 0));
        JBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarLayout = new javax.swing.GroupLayout(Buscar);
        Buscar.setLayout(BuscarLayout);
        BuscarLayout.setHorizontalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addComponent(fConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        BuscarLayout.setVerticalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BUSCAR", Buscar);

        fModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fModificarKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("INGRESE EL NOMBRE DEL SERVICIO A MODIFICAR");

        jListEncontrados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 102, 0))); // NOI18N
        jListEncontrados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jListEncontrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEncontradosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEncontrados);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NOMBRE DEL SERVICIO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PRECIO:");

        fPrecioM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fPrecioMKeyTyped(evt);
            }
        });

        fNombreServicioM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNombreServicioMKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ESTADO:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("ID");

        FIdM.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("dólares");

        cEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "PASIVO" }));
        cEstado.setSelectedIndex(1);
        cEstado.setEnabled(false);

        JBuscarM.setBackground(new java.awt.Color(255, 51, 51));
        JBuscarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoBuscar.png"))); // NOI18N
        JBuscarM.setText("BUSCAR");
        JBuscarM.setColorHover(new java.awt.Color(153, 0, 0));
        JBuscarM.setColorNormal(new java.awt.Color(255, 51, 51));
        JBuscarM.setColorPressed(new java.awt.Color(204, 0, 0));
        JBuscarM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBuscarMActionPerformed(evt);
            }
        });

        JModificar.setBackground(new java.awt.Color(255, 51, 51));
        JModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoModificar.png"))); // NOI18N
        JModificar.setText("MODIFICAR");
        JModificar.setColorHover(new java.awt.Color(153, 0, 0));
        JModificar.setColorNormal(new java.awt.Color(255, 51, 51));
        JModificar.setColorPressed(new java.awt.Color(204, 0, 0));
        JModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar);
        Modificar.setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNombreServicioM, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FIdM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificarLayout.createSequentialGroup()
                                            .addComponent(fPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel12)))))
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(JModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addComponent(fModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIdM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNombreServicioM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFICAR", Modificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListEncontradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEncontradosValueChanged
        modificar.listaEncontradoCambiar(JModificar, cEstado, jListEncontrados, FIdM, fNombreServicioM, fPrecioM);
    }//GEN-LAST:event_jListEncontradosValueChanged

    private void fPrecioAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fPrecioAKeyTyped
        tecla.numeros(evt);
    }//GEN-LAST:event_fPrecioAKeyTyped

    private void fNombreServicioAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNombreServicioAKeyTyped
        tecla.letraMayuscula(evt);
    }//GEN-LAST:event_fNombreServicioAKeyTyped

    private void fConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fConsultarKeyTyped
      tecla.letraMayuscula(evt);
    }//GEN-LAST:event_fConsultarKeyTyped

    private void fNombreServicioMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNombreServicioMKeyTyped
       tecla.letraMayuscula(evt);
    }//GEN-LAST:event_fNombreServicioMKeyTyped

    private void fPrecioMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fPrecioMKeyTyped
      tecla.numeros(evt);
    }//GEN-LAST:event_fPrecioMKeyTyped

    private void jAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregar1ActionPerformed
        agregar.botonagregar(fId, fNombreServicioA, fPrecioA, fEstado);
        agregar.generar(fId);
    }//GEN-LAST:event_jAgregar1ActionPerformed

    private void JBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarActionPerformed
       buscar.botonBuscar(fConsultar, nuevo_doc);
    }//GEN-LAST:event_JBuscarActionPerformed

    private void JBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarMActionPerformed
        modificar.botonBuscar(fModificar, jListEncontrados);
    }//GEN-LAST:event_JBuscarMActionPerformed

    private void JModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JModificarActionPerformed
    modificar.modificar(FIdM, fNombreServicioM, fPrecioM, cEstado, jListEncontrados, fModificar);
    }//GEN-LAST:event_JModificarActionPerformed

    private void fModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fModificarKeyTyped
        tecla.letraMayuscula(evt);
    }//GEN-LAST:event_fModificarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel Buscar;
    private javax.swing.JTextField FIdM;
    private rsbuttom.RSButtonMetro JBuscar;
    private rsbuttom.RSButtonMetro JBuscarM;
    private rsbuttom.RSButtonMetro JModificar;
    private javax.swing.JPanel Modificar;
    private javax.swing.JComboBox cEstado;
    private javax.swing.JTextField fConsultar;
    private javax.swing.JTextField fEstado;
    private javax.swing.JTextField fId;
    private javax.swing.JTextField fModificar;
    private javax.swing.JTextField fNombreServicioA;
    private javax.swing.JTextField fNombreServicioM;
    private javax.swing.JTextField fPrecioA;
    private javax.swing.JTextField fPrecioM;
    private rsbuttom.RSButtonMetro jAgregar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListEncontrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nuevo_doc;
    // End of variables declaration//GEN-END:variables

    
}
